server:
  port: 8766
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyh-log/Kubernetes
          username: yyh-log
          passowrd: shu19910910